site_name: GWM Documentation
site_dir: ./public/docs
repo_url: https://github.com/Geedium/GWM
repo_name: GWM
nav:
  - About: about.md
  - Console:
      - Colors: console/colors.md
  - Core:
    - Annotations: annotations.md
    - Contorllers: controllers.md
    - App: app.md
    - Distributor: distributor.md
    - DOM (deprectated): dom.md
    - Excel: excel.md
    - PDF: pdf.md
    - Plugins: plugin.md
    - Reader: reader.md
    - Http:
        - Request: http/request.md
        - Response: http/response.md
    - Routes: routes.md
    - Schema: schema.md
    - Session: session.md
    - Patterns:
        - Singleton: patterns/singleton.md
    - XML: xml.md
    - Errors:
        - Basic: errors/basic.md
    - Interfaces:
        - IAuth: interfaces/iauth.md
        - ITemplateEngine: interfaces/itpl.md
    - Models: models.md
    - Template:
        - Engines:
            - Latte: templating/engines/latte.md
            - Twig: templating/engines/twig.md
        - Locales: templating/locales.md
        - Engine: templating/engine.md
    - Utils:
      - Agent: utils/agent.md
      - Autoloader: utils/autoloader.md
      - Debug: utils/debug.md
      - Form: utils/form.md
      - Image: utils/image.md
      - Manipulation: utils/man.md
      - Measurement: utils/measurement.md
      - Str: utils/str.md
      - Table: utils/table.md
      - Wrap: utils/wrap.md
  - Features:
      - Commerce:
          - Models:
              - Employees: employees.md
              - Categories: categories.md
              - Customers: customers.md
              - Manufacturers: manifacturers.md
              - Orders: orders.md
              - Products: products.md
          - API:
              - Tebex: tebex.md
              - Stripe: stripe.md
      - Forum:
          - Models:
            - Discussions: discussions.md
            - Categories: categories.md
            - Subtopics: subtopics.md
            - Topics: topics.md
            - Replies: replies.md
theme:
  name: material
  include_sidebar: true