#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

if(basename(getcwd()) == 'tools') {
    chdir('../');
}

require 'vendor/autoload.php';

set_time_limit(0);
$status = 0;
$task = -1;
$options = [];
$n = sizeof($argv);

if (PHP_OS_FAMILY == 'Windows') {
    echo chr(27).chr(91).'H'.chr(27).chr(91).'J';
}

function textout($message)
{
    $string = '';

    $string .= "\033[1;40m";
    $string .= $message;
    $string .= "\033[m";

    if (PHP_OS_FAMILY == 'Windows') {
        $string .= "\r\n";
    }

    echo $string;
}

function out($message)
{
    $string = '';

    $string .= "\033[1;37m";
    $string .= "\033[0;41m";
    $string .= $message;
    $string .= "\033[m";

    if (PHP_OS_FAMILY == 'Windows') {
        $string .= "\r\n";
    }

    echo $string;
}

textout('
  _____ __          __ __  __ 
 / ____|\ \        / /|  \/  |
| |  __  \ \  /\  / / | \  / |
| | |_ |  \ \/  \/ /  | |\/| |
| |__| |   \  /\  /   | |  | |
 \_____|    \/  \/    |_|  |_|

');

for ($i = 1; $i <= $n; $i++) {

    if (!$argv[$i]) {
        continue;
    }

    switch ($argv[$i]) {
        case 'cron':
            $task = 0;

            if ($i + 2 <= $n) {
                if ($argv[$i + 1] == '-f') {
                    $options['f'] = $argv[$i + 2];
                }
            }
        break;
        case 'dev':
            out("Starting PHP development server at 127.0.0.1:8080");
            \shell_exec("start http://127.0.0.1:8080/ 2>&1");
            
            $php = popen("php -S 127.0.0.1:8080 -t public 2>&1", 'r');

            while(!feof($php) == true) {
                out(fread($php, 4096));
                flush();
            }

        break;
    }
}

$time = time();
$interval = 1 * 60; // 1 minute

switch ($task) {
    case 0:

        $string = '';

        $string .= "\033[1;37m";
        $string .= "\033[0;41m";
        $string .= "Executing CRON Job!\r\n";
        $string .= "Timer: Minute";
        $string .= "\033[m";

        if (PHP_OS_FAMILY == 'Windows') {
            $string .= "\r\n";
        }

        echo $string;

        while (true) {
            if ($time + $interval < time()) {
                echo $options['f'] . "\r\n";
                $time = time();
            }
        }
}

exit($status);