#!/usr/bin/env php
<?php

$status = 0;

if (php_sapi_name() !== 'cli') {
    exit;
}

if (PHP_OS_FAMILY == 'Windows') {
    echo chr(27).chr(91).'H'.chr(27).chr(91).'J';
}

$string = '';

$string .= "\033[1;37m";
$string .= "\033[0;41m";
$string .= "Running CLI!";
$string .= "\033[m";

echo $string;

exit($status);